# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bismillah.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_checkOdometry = QtWidgets.QLabel(self.centralwidget)
        self.pb_checkOdometry.setGeometry(QtCore.QRect(-20, 0, 881, 921))
        self.pb_checkOdometry.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(0, 0, 0);")
        self.pb_checkOdometry.setText("")
        self.pb_checkOdometry.setObjectName("pb_checkOdometry")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 0, 481, 921))
        self.label_2.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.POLIJE = QtWidgets.QLabel(self.centralwidget)
        self.POLIJE.setGeometry(QtCore.QRect(970, 110, 281, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.POLIJE.setFont(font)
        self.POLIJE.setStyleSheet("color: rgb(255, 0, 0);")
        self.POLIJE.setAlignment(QtCore.Qt.AlignCenter)
        self.POLIJE.setObjectName("POLIJE")
        self.IR64 = QtWidgets.QLabel(self.centralwidget)
        self.IR64.setGeometry(QtCore.QRect(960, 40, 291, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(41)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.IR64.setFont(font)
        self.IR64.setStyleSheet("color: rgb(255, 255, 255);")
        self.IR64.setAlignment(QtCore.Qt.AlignCenter)
        self.IR64.setObjectName("IR64")
        self.refbox_group = QtWidgets.QGroupBox(self.centralwidget)
        self.refbox_group.setGeometry(QtCore.QRect(910, 200, 401, 171))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.refbox_group.setFont(font)
        self.refbox_group.setStyleSheet("color: rgb(255, 255, 255);")
        self.refbox_group.setFlat(False)
        self.refbox_group.setCheckable(False)
        self.refbox_group.setObjectName("refbox_group")
        self.layoutWidget_21 = QtWidgets.QWidget(self.refbox_group)
        self.layoutWidget_21.setGeometry(QtCore.QRect(10, 30, 381, 91))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self._5 = QtWidgets.QGridLayout(self.layoutWidget_21)
        self._5.setContentsMargins(0, 0, 0, 0)
        self._5.setSpacing(6)
        self._5.setObjectName("_5")
        self.DestPort_lb_2 = QtWidgets.QLabel(self.layoutWidget_21)
        self.DestPort_lb_2.setObjectName("DestPort_lb_2")
        self._5.addWidget(self.DestPort_lb_2, 2, 0, 1, 1)
        self.address_val_2 = QtWidgets.QLineEdit(self.layoutWidget_21)
        self.address_val_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.address_val_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.address_val_2.setObjectName("address_val_2")
        self._5.addWidget(self.address_val_2, 1, 1, 1, 1)
        self.port_val_2 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.port_val_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.port_val_2.setMaximum(32767)
        self.port_val_2.setProperty("value", 28097)
        self.port_val_2.setObjectName("port_val_2")
        self._5.addWidget(self.port_val_2, 2, 1, 1, 1)
        self.address_lb_2 = QtWidgets.QLabel(self.layoutWidget_21)
        self.address_lb_2.setObjectName("address_lb_2")
        self._5.addWidget(self.address_lb_2, 1, 0, 1, 1)
        self.layoutWidget_22 = QtWidgets.QWidget(self.refbox_group)
        self.layoutWidget_22.setGeometry(QtCore.QRect(10, 130, 381, 36))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self._6 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self._6.setContentsMargins(0, 0, 0, 0)
        self._6.setSpacing(6)
        self._6.setObjectName("_6")
        self.connectBtn_2 = QtWidgets.QPushButton(self.layoutWidget_22)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.connectBtn_2.setFont(font)
        self.connectBtn_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.connectBtn_2.setStyleSheet("background-color: rgb(0, 236, 0);")
        self.connectBtn_2.setCheckable(False)
        self.connectBtn_2.setObjectName("connectBtn_2")
        self._6.addWidget(self.connectBtn_2)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_22)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self._6.addWidget(self.line_2)
        self.disconnectBtn_2 = QtWidgets.QPushButton(self.layoutWidget_22)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.disconnectBtn_2.setFont(font)
        self.disconnectBtn_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.disconnectBtn_2.setStyleSheet("background-color: rgb(239, 0, 0);")
        self.disconnectBtn_2.setCheckable(False)
        self.disconnectBtn_2.setObjectName("disconnectBtn_2")
        self._6.addWidget(self.disconnectBtn_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._6.addItem(spacerItem)
        self._7 = QtWidgets.QHBoxLayout()
        self._7.setContentsMargins(0, 0, 0, 0)
        self._7.setSpacing(6)
        self._7.setObjectName("_7")
        self.Status_lb_2 = QtWidgets.QLabel(self.layoutWidget_22)
        self.Status_lb_2.setObjectName("Status_lb_2")
        self._7.addWidget(self.Status_lb_2)
        self.status_val_2 = QtWidgets.QLabel(self.layoutWidget_22)
        self.status_val_2.setObjectName("status_val_2")
        self._7.addWidget(self.status_val_2)
        self._6.addLayout(self._7)
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(1120, 590, 101, 23))
        self.clearBtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.clearBtn.setObjectName("clearBtn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setGeometry(QtCore.QRect(930, 400, 301, 171))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.monitor = QtWidgets.QListWidget(self.groupBox_6)
        self.monitor.setGeometry(QtCore.QRect(20, 30, 261, 131))
        self.monitor.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.monitor.setObjectName("monitor")
        self.magen_score = QtWidgets.QLCDNumber(self.centralwidget)
        self.magen_score.setGeometry(QtCore.QRect(600, 20, 51, 41))
        self.magen_score.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.magen_score.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.magen_score.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.magen_score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.magen_score.setLineWidth(0)
        self.magen_score.setDigitCount(1)
        self.magen_score.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.magen_score.setObjectName("magen_score")
        self.others_lb = QtWidgets.QLabel(self.centralwidget)
        self.others_lb.setGeometry(QtCore.QRect(680, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(11)
        self.others_lb.setFont(font)
        self.others_lb.setAutoFillBackground(False)
        self.others_lb.setStyleSheet("background-color: rgb(232, 0, 0);")
        self.others_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.others_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.others_lb.setLineWidth(0)
        self.others_lb.setTextFormat(QtCore.Qt.AutoText)
        self.others_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.others_lb.setWordWrap(False)
        self.others_lb.setObjectName("others_lb")
        self.game_time = QtWidgets.QLabel(self.centralwidget)
        self.game_time.setGeometry(QtCore.QRect(340, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(40)
        self.game_time.setFont(font)
        self.game_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_time.setObjectName("game_time")
        self.iragroccer_lb = QtWidgets.QLabel(self.centralwidget)
        self.iragroccer_lb.setGeometry(QtCore.QRect(30, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(11)
        self.iragroccer_lb.setFont(font)
        self.iragroccer_lb.setAutoFillBackground(False)
        self.iragroccer_lb.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(52, 101, 164);")
        self.iragroccer_lb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iragroccer_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.iragroccer_lb.setLineWidth(0)
        self.iragroccer_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.iragroccer_lb.setWordWrap(False)
        self.iragroccer_lb.setObjectName("iragroccer_lb")
        self.cyan_score = QtWidgets.QLCDNumber(self.centralwidget)
        self.cyan_score.setGeometry(QtCore.QRect(160, 20, 51, 41))
        self.cyan_score.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cyan_score.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cyan_score.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.cyan_score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cyan_score.setLineWidth(0)
        self.cyan_score.setDigitCount(1)
        self.cyan_score.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.cyan_score.setObjectName("cyan_score")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 230, 251))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color: rgb(204, 0, 0);\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 41, 17))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 170, 41, 17))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_16.setObjectName("label_16")
        self.lineEdit_cap2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_cap2.setGeometry(QtCore.QRect(80, 90, 141, 25))
        self.lineEdit_cap2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_cap2.setObjectName("lineEdit_cap2")
        self.lineEdit_pos2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_pos2.setGeometry(QtCore.QRect(80, 130, 141, 25))
        self.lineEdit_pos2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_pos2.setObjectName("lineEdit_pos2")
        self.lineEdit_ball2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_ball2.setGeometry(QtCore.QRect(80, 170, 141, 25))
        self.lineEdit_ball2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_ball2.setObjectName("lineEdit_ball2")
        self.lineEdit_ballPos2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_ballPos2.setGeometry(QtCore.QRect(80, 210, 141, 25))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ballPos2.setFont(font)
        self.lineEdit_ballPos2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_ballPos2.setObjectName("lineEdit_ballPos2")
        self.pb_Home1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_Home1.setGeometry(QtCore.QRect(80, 40, 89, 25))
        self.pb_Home1.setStyleSheet("background-color: rgb(164, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_Home1.setObjectName("pb_Home1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(580, 90, 230, 251))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("color: rgb(204, 0, 0);\n"
"")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 41, 17))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(10, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 170, 41, 17))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_20.setObjectName("label_20")
        self.lineEdit_cap3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_cap3.setGeometry(QtCore.QRect(80, 80, 141, 25))
        self.lineEdit_cap3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_cap3.setObjectName("lineEdit_cap3")
        self.lineEdit_pos3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_pos3.setGeometry(QtCore.QRect(80, 120, 141, 25))
        self.lineEdit_pos3.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_pos3.setObjectName("lineEdit_pos3")
        self.lineEdit_ball3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ball3.setGeometry(QtCore.QRect(80, 160, 141, 25))
        self.lineEdit_ball3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_ball3.setObjectName("lineEdit_ball3")
        self.lineEdit_ballPos3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ballPos3.setGeometry(QtCore.QRect(80, 200, 141, 25))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ballPos3.setFont(font)
        self.lineEdit_ballPos3.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_ballPos3.setObjectName("lineEdit_ballPos3")
        self.pb_Home2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_Home2.setGeometry(QtCore.QRect(90, 40, 89, 25))
        self.pb_Home2.setStyleSheet("background-color: rgb(164, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_Home2.setObjectName("pb_Home2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 390, 261, 191))
        self.groupBox_2.setStyleSheet("color : white;")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lowSpeed = QtWidgets.QLabel(self.groupBox_2)
        self.lowSpeed.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.lowSpeed.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"padding: 5px;\n"
"color : none;")
        self.lowSpeed.setObjectName("lowSpeed")
        self.medSpeed = QtWidgets.QLabel(self.groupBox_2)
        self.medSpeed.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.medSpeed.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"padding: 5px;\n"
"color : none;")
        self.medSpeed.setObjectName("medSpeed")
        self.fastSpeed = QtWidgets.QLabel(self.groupBox_2)
        self.fastSpeed.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.fastSpeed.setStyleSheet("background-color: rgb(138, 226, 52);\n"
"padding: 5px;\n"
"color : none;")
        self.fastSpeed.setObjectName("fastSpeed")
        self.lineEdit_lowSpeed = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_lowSpeed.setGeometry(QtCore.QRect(110, 30, 131, 25))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_lowSpeed.setFont(font)
        self.lineEdit_lowSpeed.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_lowSpeed.setObjectName("lineEdit_lowSpeed")
        self.lineEdit_medSpeed = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_medSpeed.setGeometry(QtCore.QRect(110, 70, 131, 25))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_medSpeed.setFont(font)
        self.lineEdit_medSpeed.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_medSpeed.setObjectName("lineEdit_medSpeed")
        self.lineEdit_fastSpeed = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_fastSpeed.setGeometry(QtCore.QRect(110, 110, 131, 25))
        self.lineEdit_fastSpeed.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_fastSpeed.setObjectName("lineEdit_fastSpeed")
        self.pb_engineOff = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_engineOff.setGeometry(QtCore.QRect(50, 150, 171, 31))
        self.pb_engineOff.setStyleSheet("background-color: rgb(92, 53, 102);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pb_engineOff.setObjectName("pb_engineOff")
        self.rb_start = QtWidgets.QPushButton(self.centralwidget)
        self.rb_start.setGeometry(QtCore.QRect(250, 350, 101, 27))
        self.rb_start.setStyleSheet("background-color: rgb(115, 210, 22);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.rb_start.setObjectName("rb_start")
        self.pb_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pb_stop.setGeometry(QtCore.QRect(360, 350, 101, 27))
        self.pb_stop.setStyleSheet("background-color: rgb(164, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_stop.setObjectName("pb_stop")
        self.pb_backHome = QtWidgets.QPushButton(self.centralwidget)
        self.pb_backHome.setGeometry(QtCore.QRect(470, 350, 101, 25))
        self.pb_backHome.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(0, 0, 0);")
        self.pb_backHome.setObjectName("pb_backHome")
        self.gb_command = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_command.setGeometry(QtCore.QRect(250, 90, 321, 71))
        self.gb_command.setStyleSheet("color: rgb(255, 255, 255);")
        self.gb_command.setObjectName("gb_command")
        self.lineEdit_command = QtWidgets.QLineEdit(self.gb_command)
        self.lineEdit_command.setGeometry(QtCore.QRect(10, 30, 201, 25))
        self.lineEdit_command.setStyleSheet("color: rgb(204, 0, 0);")
        self.lineEdit_command.setReadOnly(True)
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.pb_setHome = QtWidgets.QPushButton(self.gb_command)
        self.pb_setHome.setGeometry(QtCore.QRect(220, 30, 89, 25))
        self.pb_setHome.setStyleSheet("color: rgb(46, 52, 54);")
        self.pb_setHome.setObjectName("pb_setHome")
        self.gb_field = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_field.setGeometry(QtCore.QRect(250, 170, 321, 171))
        self.gb_field.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5%;\n"
"")
        self.gb_field.setAlignment(QtCore.Qt.AlignCenter)
        self.gb_field.setFlat(True)
        self.gb_field.setChecked(False)
        self.gb_field.setObjectName("gb_field")
        self.dummyBot7 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot7.setGeometry(QtCore.QRect(150, 40, 31, 23))
        self.dummyBot7.setStyleSheet("border : none;")
        self.dummyBot7.setObjectName("dummyBot7")
        self.dummyBot4 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot4.setGeometry(QtCore.QRect(150, 85, 31, 23))
        self.dummyBot4.setStyleSheet("border : none;")
        self.dummyBot4.setObjectName("dummyBot4")
        self.dummyBot5 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot5.setGeometry(QtCore.QRect(260, 85, 31, 23))
        self.dummyBot5.setStyleSheet("border : none;")
        self.dummyBot5.setObjectName("dummyBot5")
        self.dummyBot8 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot8.setGeometry(QtCore.QRect(260, 40, 31, 23))
        self.dummyBot8.setStyleSheet("border : none;")
        self.dummyBot8.setObjectName("dummyBot8")
        self.dummyBot6 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot6.setGeometry(QtCore.QRect(40, 40, 31, 23))
        self.dummyBot6.setStyleSheet("border : none;")
        self.dummyBot6.setObjectName("dummyBot6")
        self.dummyBot3 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot3.setGeometry(QtCore.QRect(40, 85, 31, 23))
        self.dummyBot3.setStyleSheet("border : none;")
        self.dummyBot3.setObjectName("dummyBot3")
        self.dummyBot1 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot1.setEnabled(True)
        self.dummyBot1.setGeometry(QtCore.QRect(40, 130, 31, 23))
        self.dummyBot1.setStyleSheet("border : none;")
        self.dummyBot1.setIconSize(QtCore.QSize(16, 16))
        self.dummyBot1.setChecked(False)
        self.dummyBot1.setObjectName("dummyBot1")
        self.dummyBot2 = QtWidgets.QCheckBox(self.gb_field)
        self.dummyBot2.setGeometry(QtCore.QRect(260, 130, 31, 23))
        self.dummyBot2.setStyleSheet("border : none;")
        self.dummyBot2.setObjectName("dummyBot2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 390, 531, 191))
        self.groupBox.setStyleSheet("color : white;")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.pb_trialXYT = QtWidgets.QPushButton(self.groupBox)
        self.pb_trialXYT.setGeometry(QtCore.QRect(390, 110, 101, 25))
        self.pb_trialXYT.setStyleSheet("background-color: rgb(196, 160, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_trialXYT.setObjectName("pb_trialXYT")
        self.lineEdit_trialSetY = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_trialSetY.setGeometry(QtCore.QRect(355, 70, 60, 25))
        self.lineEdit_trialSetY.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_trialSetY.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_trialSetY.setObjectName("lineEdit_trialSetY")
        self.lineEdit_trialSetT = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_trialSetT.setGeometry(QtCore.QRect(430, 70, 60, 25))
        self.lineEdit_trialSetT.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_trialSetT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_trialSetT.setObjectName("lineEdit_trialSetT")
        self.lineEdit_trialSetX = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_trialSetX.setGeometry(QtCore.QRect(280, 70, 60, 25))
        self.lineEdit_trialSetX.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_trialSetX.setText("")
        self.lineEdit_trialSetX.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_trialSetX.setObjectName("lineEdit_trialSetX")
        self.pb_trialTracking = QtWidgets.QPushButton(self.groupBox)
        self.pb_trialTracking.setGeometry(QtCore.QRect(140, 110, 101, 25))
        self.pb_trialTracking.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"color: rgb(255, 255, 255);")
        self.pb_trialTracking.setObjectName("pb_trialTracking")
        self.lineEdit_trialSetKick = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_trialSetKick.setGeometry(QtCore.QRect(30, 70, 100, 25))
        self.lineEdit_trialSetKick.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_trialSetKick.setObjectName("lineEdit_trialSetKick")
        self.pb_trialSetKick = QtWidgets.QPushButton(self.groupBox)
        self.pb_trialSetKick.setGeometry(QtCore.QRect(140, 70, 101, 25))
        self.pb_trialSetKick.setStyleSheet("background-color: rgb(164, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pb_trialSetKick.setObjectName("pb_trialSetKick")
        self.horizontalWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalWidget.setGeometry(QtCore.QRect(20, 30, 287, 31))
        self.horizontalWidget.setStyleSheet("background-color: rgb(92, 53, 102);\n"
"color : white;")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radio_trialR2 = QtWidgets.QRadioButton(self.horizontalWidget)
        self.radio_trialR2.setObjectName("radio_trialR2")
        self.horizontalLayout.addWidget(self.radio_trialR2)
        self.radio_trialR3 = QtWidgets.QRadioButton(self.horizontalWidget)
        self.radio_trialR3.setObjectName("radio_trialR3")
        self.horizontalLayout.addWidget(self.radio_trialR3)
        self.radio_trialBoth = QtWidgets.QRadioButton(self.horizontalWidget)
        self.radio_trialBoth.setObjectName("radio_trialBoth")
        self.horizontalLayout.addWidget(self.radio_trialBoth)
        self.lineEdit_ballRange = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ballRange.setGeometry(QtCore.QRect(30, 110, 100, 25))
        self.lineEdit_ballRange.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.lineEdit_ballRange.setObjectName("lineEdit_ballRange")
        self.pb_trialDribble = QtWidgets.QPushButton(self.groupBox)
        self.pb_trialDribble.setGeometry(QtCore.QRect(30, 150, 211, 25))
        self.pb_trialDribble.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.pb_trialDribble.setObjectName("pb_trialDribble")
        self.pb_trialPass = QtWidgets.QPushButton(self.groupBox)
        self.pb_trialPass.setGeometry(QtCore.QRect(280, 150, 211, 25))
        self.pb_trialPass.setStyleSheet("background-color: rgb(143, 89, 2);")
        self.pb_trialPass.setObjectName("pb_trialPass")
        self.cb_speedXYT = QtWidgets.QComboBox(self.groupBox)
        self.cb_speedXYT.setGeometry(QtCore.QRect(280, 110, 91, 25))
        self.cb_speedXYT.setStyleSheet("color: rgb(164, 0, 0);")
        self.cb_speedXYT.setObjectName("cb_speedXYT")
        self.cb_speedXYT.addItem("")
        self.cb_speedXYT.addItem("")
        self.cb_speedXYT.addItem("")
        self.cb_speedXYT.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pb_Home1, self.lineEdit_cap2)
        MainWindow.setTabOrder(self.lineEdit_cap2, self.lineEdit_pos2)
        MainWindow.setTabOrder(self.lineEdit_pos2, self.lineEdit_ball2)
        MainWindow.setTabOrder(self.lineEdit_ball2, self.lineEdit_ballPos2)
        MainWindow.setTabOrder(self.lineEdit_ballPos2, self.pb_Home2)
        MainWindow.setTabOrder(self.pb_Home2, self.lineEdit_cap3)
        MainWindow.setTabOrder(self.lineEdit_cap3, self.lineEdit_pos3)
        MainWindow.setTabOrder(self.lineEdit_pos3, self.lineEdit_ball3)
        MainWindow.setTabOrder(self.lineEdit_ball3, self.lineEdit_ballPos3)
        MainWindow.setTabOrder(self.lineEdit_ballPos3, self.lineEdit_command)
        MainWindow.setTabOrder(self.lineEdit_command, self.pb_setHome)
        MainWindow.setTabOrder(self.pb_setHome, self.dummyBot6)
        MainWindow.setTabOrder(self.dummyBot6, self.dummyBot7)
        MainWindow.setTabOrder(self.dummyBot7, self.dummyBot8)
        MainWindow.setTabOrder(self.dummyBot8, self.dummyBot3)
        MainWindow.setTabOrder(self.dummyBot3, self.dummyBot4)
        MainWindow.setTabOrder(self.dummyBot4, self.dummyBot5)
        MainWindow.setTabOrder(self.dummyBot5, self.dummyBot1)
        MainWindow.setTabOrder(self.dummyBot1, self.dummyBot2)
        MainWindow.setTabOrder(self.dummyBot2, self.rb_start)
        MainWindow.setTabOrder(self.rb_start, self.pb_stop)
        MainWindow.setTabOrder(self.pb_stop, self.pb_backHome)
        MainWindow.setTabOrder(self.pb_backHome, self.radio_trialR2)
        MainWindow.setTabOrder(self.radio_trialR2, self.radio_trialR3)
        MainWindow.setTabOrder(self.radio_trialR3, self.radio_trialBoth)
        MainWindow.setTabOrder(self.radio_trialBoth, self.lineEdit_trialSetKick)
        MainWindow.setTabOrder(self.lineEdit_trialSetKick, self.pb_trialSetKick)
        MainWindow.setTabOrder(self.pb_trialSetKick, self.lineEdit_ballRange)
        MainWindow.setTabOrder(self.lineEdit_ballRange, self.pb_trialTracking)
        MainWindow.setTabOrder(self.pb_trialTracking, self.pb_trialDribble)
        MainWindow.setTabOrder(self.pb_trialDribble, self.lineEdit_trialSetX)
        MainWindow.setTabOrder(self.lineEdit_trialSetX, self.lineEdit_trialSetY)
        MainWindow.setTabOrder(self.lineEdit_trialSetY, self.lineEdit_trialSetT)
        MainWindow.setTabOrder(self.lineEdit_trialSetT, self.pb_trialXYT)
        MainWindow.setTabOrder(self.pb_trialXYT, self.lineEdit_lowSpeed)
        MainWindow.setTabOrder(self.lineEdit_lowSpeed, self.lineEdit_medSpeed)
        MainWindow.setTabOrder(self.lineEdit_medSpeed, self.lineEdit_fastSpeed)
        MainWindow.setTabOrder(self.lineEdit_fastSpeed, self.pb_engineOff)
        MainWindow.setTabOrder(self.pb_engineOff, self.address_val_2)
        MainWindow.setTabOrder(self.address_val_2, self.port_val_2)
        MainWindow.setTabOrder(self.port_val_2, self.connectBtn_2)
        MainWindow.setTabOrder(self.connectBtn_2, self.disconnectBtn_2)
        MainWindow.setTabOrder(self.disconnectBtn_2, self.monitor)
        MainWindow.setTabOrder(self.monitor, self.clearBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nusa Barong"))
        self.POLIJE.setText(_translate("MainWindow", "POLITEKNIK NEGERI JEMBER"))
        self.IR64.setText(_translate("MainWindow", "IR-64"))
        self.refbox_group.setTitle(_translate("MainWindow", "ReefereBox"))
        self.DestPort_lb_2.setText(_translate("MainWindow", "Communication port"))
        self.address_lb_2.setText(_translate("MainWindow", "IP address"))
        self.connectBtn_2.setText(_translate("MainWindow", "Connect"))
        self.disconnectBtn_2.setText(_translate("MainWindow", "Disconnect"))
        self.Status_lb_2.setText(_translate("MainWindow", "Status:"))
        self.status_val_2.setText(_translate("MainWindow", "Not connected"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Monitor"))
        self.others_lb.setText(_translate("MainWindow", "OTHERS"))
        self.game_time.setText(_translate("MainWindow", "00:00"))
        self.iragroccer_lb.setText(_translate("MainWindow", "Nusa_Barong"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Information  R2 :"))
        self.label_13.setText(_translate("MainWindow", "Cap :"))
        self.label_14.setText(_translate("MainWindow", "Pos :"))
        self.label_15.setText(_translate("MainWindow", "Status :"))
        self.label_16.setText(_translate("MainWindow", "Ball :"))
        self.pb_Home1.setText(_translate("MainWindow", "Home R2 "))
        self.groupBox_5.setTitle(_translate("MainWindow", "Information   R3:"))
        self.label_17.setText(_translate("MainWindow", "Cap :"))
        self.label_18.setText(_translate("MainWindow", "Pos :"))
        self.label_19.setText(_translate("MainWindow", "Status :"))
        self.label_20.setText(_translate("MainWindow", "Ball :"))
        self.pb_Home2.setText(_translate("MainWindow", "Home R3"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Speed"))
        self.lowSpeed.setText(_translate("MainWindow", "Low Speed"))
        self.medSpeed.setText(_translate("MainWindow", "Med Speed"))
        self.fastSpeed.setText(_translate("MainWindow", "Fast Speed :"))
        self.pb_engineOff.setText(_translate("MainWindow", "Engine Off"))
        self.rb_start.setText(_translate("MainWindow", "START"))
        self.pb_stop.setText(_translate("MainWindow", "STOP"))
        self.pb_backHome.setText(_translate("MainWindow", "BACK HOME"))
        self.gb_command.setTitle(_translate("MainWindow", "Command"))
        self.pb_setHome.setText(_translate("MainWindow", "Set Home"))
        self.gb_field.setTitle(_translate("MainWindow", "Goal Pos"))
        self.dummyBot7.setText(_translate("MainWindow", "7"))
        self.dummyBot4.setText(_translate("MainWindow", "4"))
        self.dummyBot5.setText(_translate("MainWindow", "5"))
        self.dummyBot8.setText(_translate("MainWindow", "8"))
        self.dummyBot6.setText(_translate("MainWindow", "6"))
        self.dummyBot3.setText(_translate("MainWindow", "3"))
        self.dummyBot1.setText(_translate("MainWindow", "1"))
        self.dummyBot2.setText(_translate("MainWindow", "2"))
        self.groupBox.setTitle(_translate("MainWindow", "Robot Trial"))
        self.pb_trialXYT.setText(_translate("MainWindow", "goXYT"))
        self.lineEdit_trialSetY.setPlaceholderText(_translate("MainWindow", "Y"))
        self.lineEdit_trialSetT.setPlaceholderText(_translate("MainWindow", "T"))
        self.lineEdit_trialSetX.setPlaceholderText(_translate("MainWindow", "X"))
        self.pb_trialTracking.setText(_translate("MainWindow", "Tracking"))
        self.lineEdit_trialSetKick.setPlaceholderText(_translate("MainWindow", "Value (1-255)"))
        self.pb_trialSetKick.setText(_translate("MainWindow", "Set Kick"))
        self.label.setText(_translate("MainWindow", "Choose Robot :"))
        self.radio_trialR2.setText(_translate("MainWindow", "R2"))
        self.radio_trialR3.setText(_translate("MainWindow", "R3"))
        self.radio_trialBoth.setText(_translate("MainWindow", "Both"))
        self.lineEdit_ballRange.setPlaceholderText(_translate("MainWindow", "Ball Range"))
        self.pb_trialDribble.setText(_translate("MainWindow", "Set Dribble"))
        self.pb_trialPass.setText(_translate("MainWindow", "Passing"))
        self.cb_speedXYT.setItemText(0, _translate("MainWindow", "Speed"))
        self.cb_speedXYT.setItemText(1, _translate("MainWindow", "Low"))
        self.cb_speedXYT.setItemText(2, _translate("MainWindow", "Med"))
        self.cb_speedXYT.setItemText(3, _translate("MainWindow", "Fast"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

